### ISSUE TITLE
Confusing Conclusion

### ISSUE THREAD

**Issue by lindseyberlin** [learn-co-curriculum/dsc-roc-curves-and-auc-lab#2]
End of the lab provides an ROC plot and switches the scenario, from mushrooms to heart disease, in such a way that seems like it was written as if this whole lab dealt with heart disease data

**Comment by bpurdy-ds** [comment]
That is jarring... pondering what to do @lindseyberlin.

**Comment by bpurdy-ds** [comment]
I added a brief intro on why we are using a different ROC curve, i.e. since the mushroom ROC curve is "perfect", so we need to practice interpreting on an "imperfect" ROC curve.

**Comment by bpurdy-ds** [comment]
Closed the commit with the above changes: https://github.com/learn-co-curriculum/dsc-roc-curves-and-auc-lab/issues/2#issue-684882393
